site_name: "Compiler: Best Practices"
repo_url: https://github.com/compilerla/best-practices
edit_uri: edit/main/docs
site_url: https://compilerla.github.io/best-pratices

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css
  - styles/theme.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/compilerla
      name: Compiler on Twitter

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/compiler-la
      name: Compiler on LinkedIn

    - icon: fontawesome/brands/github
      link: https://github.com/compilerla
      name: Compiler on GitHub

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty
  - fontawesome_markdown
